extends: ["spectral:oas"]

rules:
  # OpenAPI specific rules
  info-contact: warn
  info-description: warn
  info-license: warn
  operation-description: warn
  oas3-parameter-description: warn
  operation-operationId: error
  operation-tags: warn
  operation-success-response: error

  # Security
  oas3-operation-security-defined: error

  # Paths
  path-params: error
  path-declarations-must-exist: error
  path-keys-no-trailing-slash: error

  # Schema rules
  typed-enum: error

  # Tags
  openapi-tags: warn
  tag-description: off
