"""M12 -- contract test: the running FastAPI app must not drift from openapi/eki-api-v1.0.yaml.

Design-first (Pflichtenheft §2, §5): the YAML is the single source of truth.
These checks catch the classic drift cases: a route added in code but not in
the spec, a documented route that no longer exists, an enum value added in
Pydantic only, or a version mismatch between spec and ``core/version.py``.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from api.main import app
from core.models import JobStatus, RiskLevel, ScriptFormat
from core.version import __version__

SPEC_PATH = Path(__file__).resolve().parents[1] / "openapi" / "eki-api-v1.0.yaml"

# Routes that are intentionally undocumented in the public contract.
_INTERNAL_ROUTES = {"/", "/metrics", "/docs", "/redoc", "/openapi.json", "/docs/oauth2-redirect"}


@pytest.fixture(scope="module")
def spec() -> dict:
    return yaml.safe_load(SPEC_PATH.read_text())


@pytest.fixture(scope="module")
def app_paths() -> dict[str, set[str]]:
    """{path_template: {methods}} as generated by FastAPI from the live routers."""
    generated = app.openapi()["paths"]
    result: dict[str, set[str]] = {}
    for path, ops in generated.items():
        if path in _INTERNAL_ROUTES:
            continue
        result[path] = {m for m in ops if m in {"get", "post", "put", "delete", "patch"}}
    return result


class TestVersionAndMeta:
    def test_spec_version_matches_code(self, spec):
        assert spec["info"]["version"] == __version__

    def test_openapi_version_is_3_1(self, spec):
        assert spec["openapi"].startswith("3.1")

    def test_every_operation_has_id_and_security_or_is_health(self, spec):
        for path, methods in spec["paths"].items():
            for method, op in methods.items():
                assert "operationId" in op, f"{method.upper()} {path} lacks operationId"
                if path != "/health":
                    assert op.get("security"), f"{method.upper()} {path} lacks security"


class TestPathParity:
    def test_all_app_routes_are_documented(self, spec, app_paths):
        documented = {
            p: {m for m in ops if m in {"get", "post", "put", "delete", "patch"}}
            for p, ops in spec["paths"].items()
        }
        missing = []
        for path, methods in app_paths.items():
            for method in methods:
                if method not in documented.get(path, set()):
                    missing.append(f"{method.upper()} {path}")
        assert not missing, f"routes missing in OpenAPI spec: {missing}"

    def test_all_documented_routes_exist(self, spec, app_paths):
        stale = []
        for path, ops in spec["paths"].items():
            for method in ops:
                if method in {
                    "get",
                    "post",
                    "put",
                    "delete",
                    "patch",
                } and method not in app_paths.get(path, set()):
                    stale.append(f"{method.upper()} {path}")
        assert not stale, f"documented routes not implemented: {stale}"


class TestEnumParity:
    def test_job_status_enum(self, spec):
        assert set(spec["components"]["schemas"]["JobStatus"]["enum"]) == {
            s.value for s in JobStatus
        }

    def test_risk_level_enum(self, spec):
        assert set(spec["components"]["schemas"]["RiskLevel"]["enum"]) == {
            s.value for s in RiskLevel
        }

    def test_script_format_enum(self, spec):
        assert set(spec["components"]["schemas"]["ScriptFormat"]["enum"]) == {
            s.value for s in ScriptFormat
        }

    def test_delivery_status_enum_matches_ops_router(self, spec):
        from api.routers.ops import _DELIVERY_STATES

        assert set(spec["components"]["schemas"]["DeliveryStatus"]["enum"]) == set(_DELIVERY_STATES)

    def test_dead_letter_reasons_match_workflow(self, spec):
        reasons = set(
            spec["components"]["schemas"]["DeadLetterSummary"]["properties"]["reason"]["enum"]
        )
        assert reasons == {
            "retry_window_exhausted",
            "hard_4xx",
            "pull_ttl_expired",
            "delivery_failed",
        }


class TestBehaviouralContract:
    def test_one_shot_header_documented(self, spec):
        report_200 = spec["paths"]["/v1/security/reports/{report_id}"]["get"]["responses"]["200"]
        assert "X-One-Shot" in report_200["headers"]

    def test_webhook_payload_is_content_free(self, spec):
        payload = spec["components"]["schemas"]["DeliveryFailedPayload"]
        assert set(payload["required"]) == {"job_id", "report_id", "reason", "attempts"}
        for forbidden in ("findings", "report", "assessment", "script"):
            assert forbidden not in payload["properties"]

    def test_error_response_shape_matches_runtime(self, client):
        response = client.post("/v1/security/check", json={})
        body = response.json()
        assert set(body) >= {"error", "message", "timestamp"}
        assert "detail" not in body
